### ISSUE TITLE
Cryptic error message when ROI metadata and parsing inputs disagree

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal#135]
**EDIT:**
The underlying issue of why the shape of the array did not correspond to the metadata table was actually wrong metadata that was passed initially. I mistakenly parsed this as a 4x5 sites plate and the yokogawa_to_zarr parsing follows this logic of rows & cols specified.
It's actually a 5x5 dataset though. And the metadata said as much. Thus, when it tried to process things by ROIs, that was based on the metadata. But the parsing was based on other parameters. Those two were never checked against each other and thus lead to this very hard to trace bug.

How do we avoid this?
1) Avoid different tasks relying on different ground truths. In this case, make the parsing also depend on metadata, not on rows & cols parameter. See here for an issue for that specifically: https://github.com/fractal-analytics-platform/fractal/issues/126
2) What checks would actually make sense to ensure that the metadata corresponds to the actual data on disk?

----
Original issue:

I'm trying to process some new datasets and perform illumination correction on them. But when running any of the new ROI-based tasks in the tasks branch (happens for both illumination correction and ROI-based labeling), I get an error during the ROI assignment.

```
Traceback (most recent call last):
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/parsl/dataflow/dflow.py", line 768, in sanitize_and_wrap
    new_inputs.extend([dep.result()])
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/parsl/dataflow/dflow.py", line 286, in handle_exec_update
    res = self._unwrap_remote_exception_wrapper(future)
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/parsl/dataflow/dflow.py", line 471, in _unwrap_remote_exception_wrapper
    result.reraise()
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/parsl/app/errors.py", line 131, in reraise
    reraise(t, v, tb)
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/parsl/app/errors.py", line 159, in wrapper
    return func(*args, **kwargs)  # type: ignore
  File "../../fractal/fractal_cmd.py", line 600, in app
    return dict_tasks[task](zarrurl, **kwargs_)
  File "/net/nfs4/pelkmanslab-fileserver-jluethi/data/homes/jluethi/mwe_fractal/fractal/tasks/illumination_correction.py", line 246, in illumination_correction
    data_czyx_new[ind_ch, s_z:e_z, s_y:e_y, s_x:e_x] = da.stack(
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/dask/array/core.py", line 1893, in __setitem__
    dsk = setitem_array(out, self, key, value)
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/dask/array/slicing.py", line 1868, in setitem_array
    raise ValueError(
ValueError: shape mismatch: value array of shape (21, 2160, 2560) could not be broadcast to indexing result of shape (21, 1, 2560)
```

The y indices in `data_czyx_new[ind_ch, s_z:e_z, s_y:e_y, s_x:e_x]` seem to get calculated wrong leading to a shape of 1 instead of 2160.
This happens with `/data/homes/jluethi/mwe_fractal/examples/FMI_Conny_IllumCorr/example_fmi_conny_IllumCorr_argolight.sh`, but not with the 2x2 test case. So maybe it's some edge case we haven't covered yet.

I checked the AnnData ROI table, that has been parsed correctly. All the positions are as they should be, all FOVs have the correct x & y sizes.

![Screenshot 2022-08-04 at 16 58 53](https://user-images.githubusercontent.com/18033446/182879837-15de46b3-b071-42ff-bb45-9896c1432688.png)
 
Will debug a bit further to see if I can find the source. Maybe something when all sites actually start with positive positions (no negative stage coordinates)? Or something else specific to this metadata?

**Comment by jluethi** [comment]
The `list_indices` calculated [here](https://github.com/fractal-analytics-platform/fractal/blob/bc0f4523125cac380ca51b4a1c868a94c7252f0c/fractal/tasks/illumination_correction.py#L145) appear to be fine (correct spacing in x & y dimension, nothing that would be reduced to a 1):
![Screenshot 2022-08-04 at 17 07 19](https://user-images.githubusercontent.com/18033446/182882404-bb8e43c9-3702-49c2-948b-6279de5494be.png)

**Comment by jluethi** [comment]
The issue seems to be here:
`data_czyx_new[ind_ch, s_z:e_z, s_y:e_y, s_x:e_x] = da.stack(tmp_zyx, axis=0)`

`data_czyx_new[ind_ch, s_z:e_z, s_y:e_y, s_x:e_x]` is actually just of that shape:
![Screenshot 2022-08-04 at 17 20 32](https://user-images.githubusercontent.com/18033446/182884656-984e42cf-ffb8-4cd0-910c-4c219fbe6eae.png)

Which is weird, given that the indices are: 
```
print(ind_ch, s_z,e_z, s_y,e_y, s_x,e_x)
0 0 21 8639 10799 0 2560
```

**Comment by jluethi** [comment]
Oh, I think figured it out! x & y sizes of the `data_czyx_new` were switched. Thus, the array was limited in size and sometimes only returned the left-over shapes.

Given an `data_czyx_new` like this of shape (4, 21, 8640, 12800)
![Screenshot 2022-08-04 at 17 38 01](https://user-images.githubusercontent.com/18033446/182888638-62b25a41-99b2-45b0-85d6-e3683c59d8bd.png)
 
Trying to access this with `data_czyx_new[0,0:21, 8639:10799, 0:2560]` doesn't throw an error of out of bounds indexing. It just returns an array with y size of 1. Weird behavior of dask tbh...

I wonder if this is coming from a switch up in the parsing! (would explain why the 2x2 test case still work). Will investigate whether the two metadata files differ somewhere in that aspect.

**Comment by jluethi** [comment]
Correction: The underlying issue of why the shape of the array did not correspond to the metadata table was actually wrong metadata that was passed initially. I mistakenly parsed this as a 4x5 sites plate and the yokogawa_to_zarr parsing follows this logic of rows & cols specified.
It's actually a 5x5 dataset though. And the metadata said as much. Thus, when it tried to process things by ROIs, that was based on the metadata. But the parsing was based on other parameters. Those two were never checked against each other and thus lead to this very hard to trace bug.

How do we avoid this?
1) Avoid different tasks relying on different ground truths. In this case, make the parsing also depend on metadata, not on rows & cols parameter. See here for an issue for that specifically: https://github.com/fractal-analytics-platform/fractal/issues/126
2) What checks would actually make sense to ensure that the metadata corresponds to the actual data on disk?

**Comment by jluethi** [comment]
After giving it some thought, I think #126 is the only case of Fractal taking duplicate inputs (getting the same info from two places) that I can think of. If someone can think of other issues where this comes up, please open a separate issue for it.
Closing this for now as we'll address the root cause in #126
