### ISSUE TITLE
`NotRenderableError` in `dataset show`

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal#255]
```
$ fractal dataset show 1 1
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:root:Namespace(batch=False, cmd='dataset', dataset_id=1, json=False, password=None, project_id=1, subcmd='show', user=None, v=0)
DEBUG:root:AuthClient test@me.com test
DEBUG:httpx._client:HTTP Request: POST http://localhost:8000/auth/token/login "HTTP/1.1 200 OK"
DEBUG:httpx._client:HTTP Request: GET http://localhost:8000/api/v1/dataset/1/1 "HTTP/1.1 200 OK"
/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/fractal/client/cmd/_dataset.py:85 dataset_show
    res.json(): {
        'name': 'input-ds',
        'project_id': 1,
        'type': 'image',
        'meta': {},
        'read_only': True,
        'id': 1,
        'resource_list': [
            {
                'path': '/data/active/fractal/3D/PelkmansLab/CardiacMultiplexing/Cycle1_5x5_10wells_constantZ',
                'glob_pattern': '*.png',
                'id': 1,
                'dataset_id': 1,
            },
        ],
    } (dict) len=7
DEBUG:root:200
Traceback (most recent call last):
  File "/data/homes/fractal/.conda/envs/fractal/bin/fractal", line 8, in <module>
    sys.exit(run())
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/fractal/__main__.py", line 7, in run
    asyncio.run(main())
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/fractal/client/client.py", line 61, in main
    interface = await handle()
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/fractal/client/client.py", line 53, in handle
    interface = await handler(client, **vars(args))
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/fractal/client/cmd/__init__.py", line 54, in dataset
    iface = await dataset_show(client, **kwargs)
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/fractal/client/cmd/_dataset.py", line 107, in dataset_show
    table_res.add_row(*dataset.resource_list)
  File "/data/homes/fractal/.conda/envs/fractal/lib/python3.8/site-packages/rich/table.py", line 460, in add_row
    raise errors.NotRenderableError(
rich.errors.NotRenderableError: unable to render ResourceRead; a string or other renderable object is required
```

**Comment by tcompa** [comment]
More info

The relevant code block is
```python
async def dataset_show(
    client: AuthClient, *, project_id: int, dataset_id: int, **kwargs
) -> BaseInterface:
    res = await client.get(
        f"{settings.BASE_URL}/dataset/{project_id}/{dataset_id}"
    )
    from devtools import debug
    from rich.console import Group

    debug(res.json())
    dataset = check_response(res, expected_status_code=200, coerce=DatasetRead)

    if kwargs.get("json", False):
        return RichJsonInterface(retcode=0, data=dataset.dict())
    else:
        table = Table(title="Dataset")
        table.add_column("Id", style="cyan", no_wrap=True)
        table.add_column("Name", justify="right", style="green")
        table.add_column("Type", style="white")
        table.add_column("Meta", justify="center")
        table.add_column("Read only", justify="center")

        table.add_row(
            str(dataset.id),
            dataset.name,
            dataset.type,
            json.dumps(dataset.meta, indent=2),
            "✅" if dataset.read_only else "❌",
        )
        debug(dataset.resource_list)
        table_res = Table(title="Resources")
        table_res.add_column("Resource List", justify="center", style="yellow")
        table_res.add_row(*dataset.resource_list)
        group = Group(table, table_res)
        return RichConsoleInterface(retcode=0, data=group)
```
and we are in the `else` branch, with
```python
    dataset.resource_list: [
        ResourceRead(
            path='../images/10.5281_zenodo.7059515',
            glob_pattern='*.png',
            id=1,
            dataset_id=1,
        ),
    ] (list) len=1
```
