### ISSUE TITLE
fractal dataset show triggers `errors.NotRenderableError`

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal#268]
```
> fractal dataset show 1 1
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:root:Namespace(batch=False, cmd='dataset', dataset_id=1, json=False, password=None, project_id=1, subcmd='show', user=None, v=0)
DEBUG:root:AuthClient test@me.com test
DEBUG:httpx._client:HTTP Request: POST http://localhost:8000/auth/token/login "HTTP/1.1 200 OK"
DEBUG:httpx._client:HTTP Request: GET http://localhost:8000/api/v1/dataset/1/1 "HTTP/1.1 200 OK"
/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/fractal/client/cmd/_dataset.py:85 dataset_show
    res.json(): {
        'name': 'input-ds',
        'project_id': 1,
        'type': 'image',
        'meta': {},
        'read_only': True,
        'id': 1,
        'resource_list': [
            {
                'path': '/data/active/jluethi/20200810-CardiomyocyteDifferentiation14/Cycle1/images_renamed',
                'glob_pattern': '*.png',
                'id': 1,
                'dataset_id': 1,
            },
        ],
    } (dict) len=7
DEBUG:root:200
Traceback (most recent call last):
  File "/data/homes/jluethi/.conda/envs/fractal/bin/fractal", line 8, in <module>
    sys.exit(run())
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/fractal/__main__.py", line 7, in run
    asyncio.run(main())
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/fractal/client/client.py", line 61, in main
    interface = await handle()
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/fractal/client/client.py", line 53, in handle
    interface = await handler(client, **vars(args))
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/fractal/client/cmd/__init__.py", line 54, in dataset
    iface = await dataset_show(client, **kwargs)
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/fractal/client/cmd/_dataset.py", line 107, in dataset_show
    table_res.add_row(*dataset.resource_list)
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/rich/table.py", line 460, in add_row
    raise errors.NotRenderableError(
rich.errors.NotRenderableError: unable to render ResourceRead; a string or other renderable object is required
```

**Comment by tcompa** [comment]
Ref https://github.com/fractal-analytics-platform/fractal/issues/255

we should just release a new version

**Comment by jluethi** [comment]
My bad, this is a duplicate then :)

**Comment by tcompa** [comment]
> we should just release a new version

Done (`0.2.2`)
