### ISSUE TITLE
Submitting as 2 different users to the same server leads to 500 Internal Server Error

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal#276]
I've been trying to submit similar jobs to the cluster using 2 different users. This leads to an internal server error when the second user submits jobs:

```
INFO:     127.0.0.1:39012 - "POST /api/v1/project/apply/ HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/fractal_server/app/api/v1/project.py", line 148, in apply_workflow
    project, input_dataset = (await db.execute(stm)).one()
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 1191, in one
    return self._only_one_row(
  File "/data/homes/jluethi/.conda/envs/fractal/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 562, in _only_one_row
    raise exc.NoResultFound(
sqlalchemy.exc.NoResultFound: No row was found when one was required
```

It's using different project names, dataset names, workflow names and output paths. I don't see any other error messages on the server side. The client side just reports this, without an error message.

```
DEBUG:root:500
ERROR:root:Server returned 500
ERROR:root:Original request: POST http://localhost:8000/api/v1/project/2/2
ERROR:root:Original payload: {"path": "../images/10.5281_zenodo.7057076", "glob_pattern": "*.png"}
ERROR:root:Server error message: {}

ERROR:root:Terminating.

```

Individually, both examples run. If I run one after the other without restarting the server, I get this error.

**Comment by jluethi** [comment]
Ah, the `aux_extract_from_simple_json.py` file is script.py, right? I'll be trying thing with that updated version from above :)

**Comment by tcompa** [comment]
A working example is available in https://github.com/fractal-analytics-platform/fractal/tree/84_wrong_IDs_in_examples/examples/01_cardio_tiny_dataset. I'll comment a bit more about it later.
