### ISSUE TITLE
Error upon project creation

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal#342]
```python traceback
$ fractal project new asd /tmp

DEBUG:asyncio:Using selector: EpollSelector
DEBUG:root:Namespace(batch=False, cmd='project', dataset=None, json=False, name='asd', password=None, path='/tmp', slurm_user=None, subcmd='new', user=None, v=0)
INFO:root:name='asd' project_dir='/tmp' read_only=False slug=None default_dataset_name='default'
DEBUG:httpx._client:HTTP Request: POST http://localhost:8002/auth/token/login "HTTP/1.1 200 OK"
DEBUG:httpx._client:HTTP Request: POST http://localhost:8002/api/v1/project/ "HTTP/1.1 201 Created"
DEBUG:root:201
Traceback (most recent call last):
  File "/data/homes/test01/.conda/envs/fractal-client-v1/bin/fractal", line 8, in <module>
    sys.exit(run())
  File "/data/homes/test01/.conda/envs/fractal-client-v1/lib/python3.8/site-packages/fractal/__main__.py", line 7, in run
    asyncio.run(main())
  File "/data/homes/test01/.conda/envs/fractal-client-v1/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/data/homes/test01/.conda/envs/fractal-client-v1/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/data/homes/test01/.conda/envs/fractal-client-v1/lib/python3.8/site-packages/fractal/client.py", line 65, in main
    interface = await handle()
  File "/data/homes/test01/.conda/envs/fractal-client-v1/lib/python3.8/site-packages/fractal/client.py", line 55, in handle
    interface = await handler(client, **vars(args))
  File "/data/homes/test01/.conda/envs/fractal-client-v1/lib/python3.8/site-packages/fractal/cmd/__init__.py", line 41, in project
    iface = await project_create(client, batch=batch, **kwargs)
  File "/data/homes/test01/.conda/envs/fractal-client-v1/lib/python3.8/site-packages/fractal/cmd/_project.py", line 36, in project_create
    project = check_response(res, expected_status_code=201, coerce=ProjectRead)
  File "/data/homes/test01/.conda/envs/fractal-client-v1/lib/python3.8/site-packages/fractal/response.py", line 40, in check_response
    return coerce(**data)
  File "/data/homes/test01/.conda/envs/fractal-client-v1/lib/python3.8/site-packages/sqlmodel/main.py", line 506, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for ProjectRead
slug
  field required (type=value_error.missing)
```

**Comment by tcompa** [comment]
Is `Project.slug` an attribute we actually use anywhere?

**Comment by tcompa** [comment]
Fixed with https://github.com/fractal-analytics-platform/fractal/commit/c08343c2f742e78531d18965297df1f2a9e22ba4
