### ISSUE TITLE
Error when using `fractal workflow job-status`

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal#362]
When trying to use the new job-status command, I run into this error:
```
fractal workflow job-status --job-id 5

DEBUG:asyncio:Using selector: EpollSelector
DEBUG:root:Namespace(batch=False, cmd='workflow', job_id='5', json=False, password=None, slurm_user=None, subcmd='job-status', user=None, v=0)
DEBUG:httpx._client:HTTP Request: POST http://localhost:8002/auth/token/login "HTTP/1.1 200 OK"
DEBUG:httpx._client:HTTP Request: GET http://localhost:8002/api/v1/job/5 "HTTP/1.1 200 OK"
DEBUG:root:200
Traceback (most recent call last):
  File "/ENV/FOLDER/fractal-client-v1-a5/bin/fractal", line 8, in <module>
    sys.exit(run())
  File "/ENV/FOLDER/fractal-client-v1-a5/lib/python3.8/site-packages/fractal/__main__.py", line 7, in run
    asyncio.run(main())
  File "/ENV/FOLDER/fractal-client-v1-a5/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/ENV/FOLDER/fractal-client-v1-a5/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/ENV/FOLDER/fractal-client-v1-a5/lib/python3.8/site-packages/fractal/client.py", line 66, in main
    interface.show()
  File "/ENV/FOLDER/fractal-client-v1-a5/lib/python3.8/site-packages/fractal/interface.py", line 41, in show
    print_json(data=self.data)
  File "/ENV/FOLDER/fractal-client-v1-a5/lib/python3.8/site-packages/rich/__init__.py", line 106, in print_json
    get_console().print_json(
  File "/ENV/FOLDER/fractal-client-v1-a5/lib/python3.8/site-packages/rich/console.py", line 1749, in print_json
    json_renderable = JSON.from_data(
  File "/ENV/FOLDER/fractal-client-v1-a5/lib/python3.8/site-packages/rich/json.py", line 84, in from_data
    json = dumps(
  File "/ENV/FOLDER/fractal-client-v1-a5/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/ENV/FOLDER/fractal-client-v1-a5/lib/python3.8/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/ENV/FOLDER/fractal-client-v1-a5/lib/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/ENV/FOLDER/fractal-client-v1-a5/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/ENV/FOLDER/fractal-client-v1-a5/lib/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/ENV/FOLDER/fractal-client-v1-a5/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
```

I wasn't fully sure that I used the correct job-id. The apply output was the following:
```
{
  "project_id": 5,
  "input_dataset_id": 9,
  "output_dataset_id": 10,
  "workflow_id": 5,
  "overwrite_input": false,
  "worker_init": "TBD"
  "working_dir": null,
  "id": 5,
  "start_timestamp": "2022-12-15 14:10:12.563838",
  "status": "submitted",
  "log": null,
  "history": null
}
```

Is it the `id` or the `workflow_id` that would be the relevant one here? Both were 5 anyway in that case though.

**Comment by tcompa** [comment]
Can you specify the client version?

**Comment by tcompa** [comment]
Could you re-try with 1.0.0a6?

(re-opening, waiting for feedback)

**Comment by tcompa** [comment]
> Is it the id or the workflow_id that would be the relevant one here? Both were 5 anyway in that case though.

That's right.

**Comment by jluethi** [comment]
> That's right.

=> which one? `id` or `workflow_id`?

**Comment by tcompa** [comment]
My bad. The `id` is the one that matters.

What you are looking at is a job object (technically it's an `ApplyWorkflowRead` object), and its `id` attribute is what we later call `job_id`. You can see this from the fact that it also has info about datasets.

The job is also associated to a (more abstract) workflow, which has its own `workflow_id`. This is not useful for querying job statuses.

**Comment by jluethi** [comment]
ok, now the command works! :)

The `log` part formatting returned isn't very readable when there is a large error message, but already good to get access to it! 👏🏻
