### ISSUE TITLE
In `_get_fresh_token`, handle a `JSONDecodeError`

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal#380]
```
DEBUG:root:Namespace(batch=False, cmd='task', json=False, package='fractal-tasks-core', package_extras=None, package_version='0.6.5', password=None, private=False, python_version=None, slurm_user=None, subcmd='collect', user=None, v=0)
DEBUG:httpx._client:HTTP Request: POST http://172.23.28.82:8010/auth/token/login "HTTP/1.1 500 Internal Server Error"
Traceback (most recent call last):
  File "/data/homes/test01/.conda/envs/fractal-client-1.0.0a9/bin/fractal", line 8, in <module>
    sys.exit(run())
  File "/data/homes/test01/.conda/envs/fractal-client-1.0.0a9/lib/python3.8/site-packages/fractal/__main__.py", line 7, in run
    asyncio.run(main())
  File "/data/homes/test01/.conda/envs/fractal-client-1.0.0a9/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/data/homes/test01/.conda/envs/fractal-client-1.0.0a9/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/data/homes/test01/.conda/envs/fractal-client-1.0.0a9/lib/python3.8/site-packages/fractal/client.py", line 65, in main
    interface = await handle()
  File "/data/homes/test01/.conda/envs/fractal-client-1.0.0a9/lib/python3.8/site-packages/fractal/client.py", line 55, in handle
    interface = await handler(client, **vars(args))
  File "/data/homes/test01/.conda/envs/fractal-client-1.0.0a9/lib/python3.8/site-packages/fractal/cmd/__init__.py", line 142, in task
    iface = await task_collect_pip(client, batch=batch, **kwargs)
  File "/data/homes/test01/.conda/envs/fractal-client-1.0.0a9/lib/python3.8/site-packages/fractal/cmd/_task.py", line 40, in task_collect_pip
    res = await client.post(
  File "/data/homes/test01/.conda/envs/fractal-client-1.0.0a9/lib/python3.8/site-packages/fractal/authclient.py", line 119, in post
    headers=await self.auth.header(), *args, **kwargs
  File "/data/homes/test01/.conda/envs/fractal-client-1.0.0a9/lib/python3.8/site-packages/fractal/authclient.py", line 77, in header
    token = await self.__call__()
  File "/data/homes/test01/.conda/envs/fractal-client-1.0.0a9/lib/python3.8/site-packages/fractal/authclient.py", line 82, in __call__
    await self._get_fresh_token()
  File "/data/homes/test01/.conda/envs/fractal-client-1.0.0a9/lib/python3.8/site-packages/fractal/authclient.py", line 44, in _get_fresh_token
    "Error: could not obtain token. Is the user registered?\n"
  File "/data/homes/test01/.conda/envs/fractal-client-1.0.0a9/lib/python3.8/site-packages/httpx/_models.py", line 752, in json
    return jsonlib.loads(self.text, **kwargs)
  File "/data/homes/test01/.conda/envs/fractal-client-1.0.0a9/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/data/homes/test01/.conda/envs/fractal-client-1.0.0a9/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/homes/test01/.conda/envs/fractal-client-1.0.0a9/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
To quickly see whether task collection is complete, issue the command
fractal task list
```

**Comment by tcompa** [comment]
Write a test where:
1. `register_user` fixture is not used, but rather implemented by hand with a custom user email and password;
2. ~~`invoke` is not used, but rather implemented by hand, with a custom user email and password (that is, not using the user/pwd from environment variables -- see code of `handle`;~~
3. Even better than 2, call e.g. `invoke("--user MYUSER --password MYPASSWORD task list")`, where the credentials are the same as in 1
4. Make a simple API call, e.g. `task list`, as in 3
5. Make an API call with wrong credentials, e.g. MYUSERNEW. See how it fails

Note that points 2-5 probably could be replaced by simply creating an `AuthClient` object and then calling its `_get_fresh_token` method.

**Comment by tcompa** [comment]
Even simpler and more relevant, make sure that
```python
        res = await self.client.post(
            f"{settings.FRACTAL_SERVER}/auth/token/login", data=data
        )
        if res.status_code != 200:
            raise AuthenticationError(
                "Error: could not obtain token. Is the user registered?\n"
                f"{res.json()}\n"
            )
```
is correct.

That is, when we receive a 500, is there an actual `res.json()`?

**Comment by jluethi** [comment]
Ah, I've also been hitting this JSONDecodeError in some unexpected places recently with the CLI client. Would make sense if it's related to token validity somehow

**Comment by tcompa** [comment]
The JSONDecodeError is fixed with https://github.com/fractal-analytics-platform/fractal/commit/d91c95ab9a9d39018cff3f72292e1124720793ca.

We tried to reproduce the actual wrong-token error, but we failed (see https://github.com/fractal-analytics-platform/fractal/pull/477).

Closing for now, let's re-open the first time someone hits it again.
