### ISSUE TITLE
Clean up `fractal register` command

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal#395]
Multiple issues:

1. `from .config import settings` (in `client.py`) is executed independently on whether the command needs those settings or not. For instance `register` and `version` should work out of the box, without those variables being set. Example of this failing:
```
$ fractal register me@me.com slurm_user -p pwd

Traceback (most recent call last):
  File "/data/homes/test01/.conda/envs/fractal-client-1.0.0rc0/bin/fractal", line 5, in <module>
    from fractal.__main__ import run
  File "/data/homes/test01/.conda/envs/fractal-client-1.0.0rc0/lib/python3.8/site-packages/fractal/__main__.py", line 3, in <module>
    from fractal.client import main
  File "/data/homes/test01/.conda/envs/fractal-client-1.0.0rc0/lib/python3.8/site-packages/fractal/client.py", line 23, in <module>
    from . import cmd
  File "/data/homes/test01/.conda/envs/fractal-client-1.0.0rc0/lib/python3.8/site-packages/fractal/cmd/__init__.py", line 3, in <module>
    from ..authclient import AuthClient
  File "/data/homes/test01/.conda/envs/fractal-client-1.0.0rc0/lib/python3.8/site-packages/fractal/authclient.py", line 7, in <module>
    from .config import settings
  File "/data/homes/test01/.conda/envs/fractal-client-1.0.0rc0/lib/python3.8/site-packages/fractal/config.py", line 32, in <module>
    class Settings(BaseSettings):
  File "/data/homes/test01/.conda/envs/fractal-client-1.0.0rc0/lib/python3.8/site-packages/fractal/config.py", line 38, in Settings
    FRACTAL_USER: str = fail_getenv("FRACTAL_USER")
  File "/data/homes/test01/.conda/envs/fractal-client-1.0.0rc0/lib/python3.8/site-packages/fractal/config.py", line 25, in fail_getenv
    raise ValueError(f"Must provide environment variable {key}")
ValueError: Must provide environment variable FRACTAL_USER
(fractal-client-1.0.0rc0) test01@pelkmanslab-slurm-master-0
```
2. After this is fixed, it will become clear that a command like
```
$ fractal -u me@me.com -p pwd register me@me.com slurm_user -p pwd
```
makes no sense, because the first `-u` and `-p` arguments (the ones for `fractal`) are not required nor used. Let's handle this, e.g. by adding a warning or error if there are multiples `-u/-p` set.

**Comment by tcompa** [comment]
Closed with #406
