### ISSUE TITLE
Improve log formatting (server or client?)

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal#399]
```
$ fractal job status 1
{
  "project_id": 1,
  "input_dataset_id": 1,
  "output_dataset_id": 2,
  "workflow_id": 1,
  "overwrite_input": false,
  "worker_init": "export CELLPOSE_LOCAL_MODELS_PATH=/data/homes/test01/.cache/CELLPOSE_LOCAL_MODELS_PATH\nexport NUMBA_CACHE_DIR=/data/homes/test01/.cache/NUMBA_CACHE_DIR\nexport NAPARI_CONFIG=/data/homes/test01/.cache/NAPARI_CACHE_DIR\nexport XDG_CONFIG_HOME=/data/homes/test01/.cache/XDG\n",
  "working_dir": "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/fractal-demos/examples/server/artifacts/workflow_000001_job_000001",
  "id": 1,
  "start_timestamp": "2023-01-11 14:43:29.254846",
  "status": "failed",
  "history": null
}

This is the job log:

TASK ERROR:Task id: 1 (Create OME-Zarr structure), e.workflow_task_order=0
TRACEBACK:
(['Traceback (most recent call last):\n', '  File "/data/homes/fractal/anaconda3/envs/fractal-server-1.0.0rc1/lib/python3.8/site-packages/fractal_server/app/runner/_common.py", line 204, in call_single_task\n    raise e\n', '  File "/data/homes/fractal/anaconda3/envs/fractal-server-1.0.0rc1/lib/python3.8/site-packages/fractal_server/app/runner/_common.py", line 197, in call_single_task\n    _call_command_wrapper(\n', '  File "/data/homes/fractal/anaconda3/envs/fractal-server-1.0.0rc1/lib/python3.8/site-packages/fractal_server/app/runner/_common.py", line 130, in _call_command_wrapper\n    raise TaskExecutionError(err)\n', 'fractal_server.app.runner.common.TaskExecutionError: 2023-01-11 14:43:43,846; INFO; START create_ome_zarr task\nTraceback (most recent call last):\n  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/fractal_tasks_core/create_ome_zarr.py", line 396, in <module>\n    run_fractal_task(\n  File "/data/homes/fractal/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/fractal_tasks_core/_utils.py", line 104, in run_fractal_task\n    metadata_update = task_function(**task_args.dict())\n  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/fractal_tasks_core/create_ome_zarr.py", line 140, in create_ome_zarr\n    raise Exception(f"{info}ERROR: No plates detected")\nException: Listing all plates/channels from /data/homes/test01/fractal-demos/examples/01_cardio_tiny_dataset/../images/10.5281_zenodo.7059515/*.png\nPlates:   []\nChannels: []\nERROR: No plates detected\n\n'], ('2023-01-11 14:43:43,846; INFO; START create_ome_zarr task\nTraceback (most recent call last):\n  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/fractal_tasks_core/create_ome_zarr.py", line 396, in <module>\n    run_fractal_task(\n  File "/data/homes/fractal/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/fractal_tasks_core/_utils.py", line 104, in run_fractal_task\n    metadata_update = task_function(**task_args.dict())\n  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/fractal_tasks_core/create_ome_zarr.py", line 140, in create_ome_zarr\n    raise Exception(f"{info}ERROR: No plates detected")\nException: Listing all plates/channels from /data/homes/test01/fractal-demos/examples/01_cardio_tiny_dataset/../images/10.5281_zenodo.7059515/*.png\nPlates:   []\nChannels: []\nERROR: No plates detected\n',))
```

**Comment by jluethi** [comment]
The desired improvement is for the Traceback? If so, +1 on that! If not, I can open another issue for this :) Would be great to actually have line breaks there instead of the \n.
(wasn't that formatted nicer just before Christmas?)

**Comment by tcompa** [comment]
> The desired improvement is for the Traceback?

Yes.

>  (wasn't that formatted nicer just before Christmas?)

Partly, in https://github.com/fractal-analytics-platform/fractal/issues/364. I think the difference is whether the traceback is a single line a list of lines, and in the second case getting the `str()` of a list (or tuple) is not producing clean output.

It won't be hard to fix
