### ISSUE TITLE
ModuleNotFoundError: No module named 'fastapi_users'

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal#408]
Error coming from some client command:

```
Traceback (most recent call last):
  File "/data/homes/test01/.conda/envs/fractal-client-1.0.0rc2-tommaso/bin/fractal", line 5, in <module>
    from fractal.__main__ import run
  File "/data/homes/test01/.conda/envs/fractal-client-1.0.0rc2-tommaso/lib/python3.8/site-packages/fractal/__main__.py", line 3, in <module>
    from fractal.client import main
  File "/data/homes/test01/.conda/envs/fractal-client-1.0.0rc2-tommaso/lib/python3.8/site-packages/fractal/client.py", line 23, in <module>
    from . import cmd
  File "/data/homes/test01/.conda/envs/fractal-client-1.0.0rc2-tommaso/lib/python3.8/site-packages/fractal/cmd/__init__.py", line 26, in <module>
    from ._user import user_delete
  File "/data/homes/test01/.conda/envs/fractal-client-1.0.0rc2-tommaso/lib/python3.8/site-packages/fractal/cmd/_user.py", line 5, in <module>
    from ..common.schemas.user import UserCreate
  File "/data/homes/test01/.conda/envs/fractal-client-1.0.0rc2-tommaso/lib/python3.8/site-packages/fractal/common/schemas/user.py", line 4, in <module>
    from fastapi_users import schemas
ModuleNotFoundError: No module named 'fastapi_users'
```

**Comment by tcompa** [comment]
Temporary fix: `pip install fastapi_users`
