### ISSUE TITLE
Duplication and weird order in job log upon hitting an error

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal#456]
When I ran into this recent task error https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/343 and checked the status with `fractal job show`, the log gets displayed in a weird fashion. Instead of just having this error log once, it shows what looks like 3 versions of the error log intermixed:

```
This is the job log:

TASK ERROR:Task id: 47 (Cellpose Segmentation), e.workflow_task_order=4
TRACEBACK:
Traceback (most recent call last):
  File "/data/homes/fractal/anaconda3/envs/fractal-server-1.1.0a1/lib/python3.9/site-packages/fractal_server/app/runner/_common.py", line 373, in call_single_parallel_task
    raise e
  File "/data/homes/fractal/anaconda3/envs/fractal-server-1.1.0a1/lib/python3.9/site-packages/fractal_server/app/runner/_common.py", line 366, in call_single_parallel_task
    _call_command_wrapper(
  File "/data/homes/fractal/anaconda3/envs/fractal-server-1.1.0a1/lib/python3.9/site-packages/fractal_server/app/runner/_common.py", line 179, in _call_command_wrapper
    raise TaskExecutionError(err)
fractal_server.app.runner.common.TaskExecutionError: Matplotlib created a temporary config/cache directory at /tmp/matplotlib-sz_5jctt because the default path (/data/homes/fractal/.cache/matplotlib) is not a writa
ble directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
2023-03-08 14:57:21,158; INFO; START cellpose_segmentation task
2023-03-08 14:57:21,158; INFO; /net/nfs4/pelkmanslab-fileserver-jluethi/data/homes/jluethi/v1_fractal/fractal-demos/examples/01_cardio_tiny_dataset/tmp_cp_cyto2/output/20200812-CardiomyocyteDifferentiation14-Cycle1
_mip.zarr/B/03/0/
2023-03-08 14:57:21,200; INFO; [B_03_0] data_zyx.shape=(1, 540, 1280)
2023-03-08 14:57:21,248; INFO; new_labels=['nuclei']
2023-03-08 14:57:21,248; INFO; existing_labels=[]
2023-03-08 14:57:21,260; INFO; [B_03_0] /net/nfs4/pelkmanslab-fileserver-jluethi/data/homes/jluethi/v1_fractal/fractal-demos/examples/01_cardio_tiny_dataset/tmp_cp_cyto2/output/20200812-CardiomyocyteDifferentiation
14-Cycle1_mip.zarr/B/03/0/labels/nuclei/0
2023-03-08 14:57:21,266; INFO; [B_03_0] mask will have shape (1, 540, 1280) and chunks ((1,), (540,), (1280,))
2023-03-08 14:57:21,268; INFO; TORCH CUDA version not installed/working.
2023-03-08 14:57:21,268; INFO; >> cyto2 << model set to be used
2023-03-08 14:57:21,269; INFO; Downloading: "https://www.cellpose.org/models/ModelInCellposeZoo.cyto2torch_0" to /data/homes/jluethi/.cache/CELLPOSE_LOCAL_MODELS_PATH/ModelInCellposeZoo.cyto2torch_0

Traceback (most recent call last):
  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR_110a1/.fractal/fractal-tasks-core0.8.0/venv/lib/python3.9/site-packages/fractal_tas
ks_core/cellpose_segmentation.py", line 642, in <module>
    run_fractal_task(
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR_110a1/.fractal/fractal-tasks-core0.8.0/venv/lib/python3.9/site-packages/fractal_tasks_core/_utils.py", line 91, in run_fra
ctal_task
    metadata_update = task_function(**task_args.dict(exclude_unset=True))
  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR_110a1/.fractal/fractal-tasks-core0.8.0/venv/lib/python3.9/site-packages/fractal_tas
ks_core/cellpose_segmentation.py", line 460, in cellpose_segmentation
    model = models.CellposeModel(gpu=gpu, model_type=model_type)
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR_110a1/.fractal/fractal-tasks-core0.8.0/venv/lib/python3.9/site-packages/cellpose/models.py", line 346, in __init__
    pretrained_model = [model_path(pretrained_model_string, j, self.torch) for j in model_range]
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR_110a1/.fractal/fractal-tasks-core0.8.0/venv/lib/python3.9/site-packages/cellpose/models.py", line 346, in <listcomp>
    pretrained_model = [model_path(pretrained_model_string, j, self.torch) for j in model_range]
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR_110a1/.fractal/fractal-tasks-core0.8.0/venv/lib/python3.9/site-packages/cellpose/models.py", line 30, in model_path
    return cache_model_path(basename)
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR_110a1/.fractal/fractal-tasks-core0.8.0/venv/lib/python3.9/site-packages/cellpose/models.py", line 43, in cache_model_path
    utils.download_url_to_file(url, cached_file, progress=True)
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR_110a1/.fractal/fractal-tasks-core0.8.0/venv/lib/python3.9/site-packages/cellpose/utils.py", line 64, in download_url_to_fi
le
    u = urlopen(url)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-1.1.0a1/lib/python3.9/urllib/request.py", line 214, in urlopen  
    return opener.open(url, data, timeout)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-1.1.0a1/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-1.1.0a1/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/data/homes/fractal/anaconda3/envs/fractal-server-1.1.0a1/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-1.1.0a1/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-1.1.0a1/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: INTERNAL SERVER ERROR


Matplotlib created a temporary config/cache directory at /tmp/matplotlib-sz_5jctt because the default path (/data/homes/fractal/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MP
LCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
2023-03-08 14:57:21,158; INFO; START cellpose_segmentation task
2023-03-08 14:57:21,158; INFO; /net/nfs4/pelkmanslab-fileserver-jluethi/data/homes/jluethi/v1_fractal/fractal-demos/examples/01_cardio_tiny_dataset/tmp_cp_cyto2/output/20200812-CardiomyocyteDifferentiation14-Cycle1
_mip.zarr/B/03/0/
2023-03-08 14:57:21,200; INFO; [B_03_0] data_zyx.shape=(1, 540, 1280)
2023-03-08 14:57:21,248; INFO; new_labels=['nuclei']
2023-03-08 14:57:21,248; INFO; existing_labels=[]
2023-03-08 14:57:21,260; INFO; [B_03_0] /net/nfs4/pelkmanslab-fileserver-jluethi/data/homes/jluethi/v1_fractal/fractal-demos/examples/01_cardio_tiny_dataset/tmp_cp_cyto2/output/20200812-CardiomyocyteDifferentiation14-Cycle1_mip.zarr/B/03/0/labels/nuclei/0
2023-03-08 14:57:21,266; INFO; [B_03_0] mask will have shape (1, 540, 1280) and chunks ((1,), (540,), (1280,))
2023-03-08 14:57:21,268; INFO; TORCH CUDA version not installed/working.
2023-03-08 14:57:21,268; INFO; >> cyto2 << model set to be used
2023-03-08 14:57:21,269; INFO; Downloading: "https://www.cellpose.org/models/ModelInCellposeZoo.cyto2torch_0" to /data/homes/jluethi/.cache/CELLPOSE_LOCAL_MODELS_PATH/ModelInCellposeZoo.cyto2torch_0

Traceback (most recent call last):
  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR_110a1/.fractal/fractal-tasks-core0.8.0/venv/lib/python3.9/site-packages/fractal_tasks_core/cellpose_segmentation.py", line 642, in <module>
    run_fractal_task(
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR_110a1/.fractal/fractal-tasks-core0.8.0/venv/lib/python3.9/site-packages/fractal_tasks_core/_utils.py", line 91, in run_fractal_task
    metadata_update = task_function(**task_args.dict(exclude_unset=True))
  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR_110a1/.fractal/fractal-tasks-core0.8.0/venv/lib/python3.9/site-packages/fractal_tasks_core/cellpose_segmentation.py", line 460, in cellpose_segmentation
    model = models.CellposeModel(gpu=gpu, model_type=model_type)
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR_110a1/.fractal/fractal-tasks-core0.8.0/venv/lib/python3.9/site-packages/cellpose/models.py", line 346, in __init__
    pretrained_model = [model_path(pretrained_model_string, j, self.torch) for j in model_range]
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR_110a1/.fractal/fractal-tasks-core0.8.0/venv/lib/python3.9/site-packages/cellpose/models.py", line 346, in <listcomp>
    pretrained_model = [model_path(pretrained_model_string, j, self.torch) for j in model_range]
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR_110a1/.fractal/fractal-tasks-core0.8.0/venv/lib/python3.9/site-packages/cellpose/models.py", line 30, in model_path
    return cache_model_path(basename)
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR_110a1/.fractal/fractal-tasks-core0.8.0/venv/lib/python3.9/site-packages/cellpose/models.py", line 43, in cache_model_path
    utils.download_url_to_file(url, cached_file, progress=True)
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR_110a1/.fractal/fractal-tasks-core0.8.0/venv/lib/python3.9/site-packages/cellpose/utils.py", line 64, in download_url_to_file
    u = urlopen(url)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-1.1.0a1/lib/python3.9/urllib/request.py", line 214, in urlopen  
    return opener.open(url, data, timeout)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-1.1.0a1/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-1.1.0a1/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/data/homes/fractal/anaconda3/envs/fractal-server-1.1.0a1/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-1.1.0a1/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-1.1.0a1/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: INTERNAL SERVER ERROR
```

See https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/343 for the error log as it appears in the .err file.
Any idea why the job show endpoint currently shows this mixed-up version of the log?

**Comment by jluethi** [comment]
Ah, have already deleted it. But I'm sure I'll run into a TaskError again sometime and will then check for it :)
